### ISSUE TITLE
404 Error on Contact page

### ISSUE THREAD

**Issue by rkalnins** [KAMSC/blog#3]
Clicking on the contact page results in a 404 Error. I can look into it unless @sidpagariya is already aware of the problem and fixing it.

**Comment by sidpagariya** [comment]
Let me also look into it... Thanks for making me aware of this!

**Comment by sidpagariya** [comment]
The Jekyll linking is broken. The correct URL is: https://kamsc.github.io/blog/contact-us.html which works, so I will have to look into this.

**Comment by sidpagariya** [comment]
Fixed, thanks a ton for pointing that out!
