### ISSUE TITLE
Text spacing on small screens

### ISSUE THREAD

**Issue by rkalnins** [KAMSC/blog#5]
On smaller screens, text is spread evenly across the screen and thus looks bad when only two or three words appear on the screen. Not urgent but would be nice before official release since most students will probably be using the mobile site.  Should be a somewhat simple CSS fix.

**Comment by sidpagariya** [comment]
I am not sure what the problem really is...
Here's a preview for iPhone 6:
<img width="1280" alt="screen shot 2017-06-14 at 6 51 14 pm" src="https://user-images.githubusercontent.com/10685754/27158005-93642256-5132-11e7-9d0b-b712475675ae.png">
And iPhone 5:
<img width="1280" alt="screen shot 2017-06-14 at 6 52 35 pm" src="https://user-images.githubusercontent.com/10685754/27158019-ac2e3c72-5132-11e7-8913-4873806bd385.png">
Here's one more:
<img width="222" alt="screen shot 2017-06-14 at 6 53 21 pm" src="https://user-images.githubusercontent.com/10685754/27158045-cd358876-5132-11e7-9737-1667fbc6e0bf.png">
Even an iPhone 4 is fine:
<img width="423" alt="screen shot 2017-06-14 at 6 55 02 pm" src="https://user-images.githubusercontent.com/10685754/27158087-094dac1c-5133-11e7-8550-9c700cdf414d.png">

**Comment by rkalnins** [comment]
Check the contact us and social media/ resources pages.  This is on iPhone 6S
<img width="641" alt="screen shot 2017-06-14 at 6 55 37 pm" src="https://user-images.githubusercontent.com/24725865/27158115-2d8cc310-5133-11e7-8107-476a524a7f59.png">

**Comment by sidpagariya** [comment]
Ok, will double check what the issue is...

**Comment by sidpagariya** [comment]
Working on it... already.
