### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by rkalnins** [KAMSC/blog#9]
Maybe lunr.js isn't the best choice for the search.  It appears as though it tends to get very slow with many larger blogs.  Check this out: [https://github.com/chinchang/super-search/](https://github.com/chinchang/super-search/)

**Comment by sidpagariya** [comment]
Will check to see what's needed for this. I already implemented RSS after seeing this post, so, it should be only a couple steps away...
EDIT: Added alpha-stage for search-feature.

**Comment by rkalnins** [comment]
I was just about to commit the alpha stage until I saw you did it already.

**Comment by sidpagariya** [comment]
@RKalnins I am yet to fix the layout and the placement of the search + making it disappear...
